--1.Check for max date in

--Annually files
select 'IMP_TRANSACT 2019', max(DTSTAMP) from [abc096].[IMP_TRANSACT_D_2019]
select 'IMP_TRANSACT 2019 #2', max(DTSTAMP) from [abc096].[IMP_TRANSACT_D_2019_B]

select 'LIFECARD 2019',max(DTSTAMP) from [abc096].[LIFECARD_2019]

select 'TRANSLOG 2019', max(DTSTAMP) from [dbo].[TRANSLOG_TRANSACT_2019]

select 'EASYPAY 2019', max(TrxDate) from [dbo].[EasyPayAgent_2019]

--Monthly files
select 'IMP_TRANSACT', max(DTSTAMP) from [abc096].IMP_TRANSACT_D_monthly

select 'LIFECARD',max(DTSTAMP) from [abc096].[LIFECARD]

select 'TRANSLOG', max(DTSTAMP) from [dbo].[TRANSLOG_TRANSACT]

select 'EASYPAY', max(TrxDate) from [dbo].[EasyPayAgent]

-- Alternate View - yearly / temp
select 'IMP_TRANSACT 2019', max(DTSTAMP) from [abc096].[IMP_TRANSACT_D_2019]
select 'IMP_TRANSACT 2019 #2', max(DTSTAMP) from [abc096].[IMP_TRANSACT_D_2019_B]
select 'IMP_TRANSACT', max(DTSTAMP) from [abc096].IMP_TRANSACT_D_monthly

select 'LIFECARD 2019',max(DTSTAMP) from [abc096].[LIFECARD_2019]
select 'LIFECARD',max(DTSTAMP) from [abc096].[LIFECARD]

select 'TRANSLOG 2019', max(DTSTAMP) from [dbo].[TRANSLOG_TRANSACT_2019]
select 'TRANSLOG', max(DTSTAMP) from [dbo].[TRANSLOG_TRANSACT]

select 'EASYPAY 2019', max(TrxDate) from [dbo].[EasyPayAgent_2019]
select 'EASYPAY', max(TrxDate) from [dbo].[EasyPayAgent]




--2. Insert monthly records to annual files

INSERT INTO [abc096].[IMP_TRANSACT_D_2019] with (TABLOCK)
           ([TBL]
           ,[TCODE]
           ,[MID]
           ,[TID]
           ,[MASK]
           ,[AMOUNT]
           ,[CURR]
           ,[INST]
           ,[GRACE]
           ,[ORIGINATOR]
           ,[DESTCOMID]
           ,[PROCCODE]
           ,[MSGID]
           ,[RESPKIND]
           ,[REVERSED]
           ,[BTBL]
           ,[BTCODE]
           ,[PROCBATCH]
           ,[ePOSBATCH]
           ,[POSDATA]
           ,[BPOSDATA]
           ,[DTSTAMP]
           ,[BDTSTAMP]
           ,[ORGSYSTAN]
           ,[DTSTAMP_INSERT]
           ,[ProductID]
           ,[USERDATA]
           ,[BORGSYSTAN]
           ,[AUTHCODE]
           ,[CASHIERINFO]
           ,[DMID]
           ,[DTID]
           ,[CASHBACK]
           ,[BONUSRED]
           ,[PBGAMOUNT]
           ,[RRN])
     select
          [TBL]
           ,[TCODE]
           ,[MID]
           ,[TID]
           ,[MASK]
           ,[AMOUNT]
           ,[CURR]
           ,[INST]
           ,[GRACE]
           ,[ORIGINATOR]
           ,[DESTCOMID]
           ,[PROCCODE]
           ,[MSGID]
           ,[RESPKIND]
           ,[REVERSED]
           ,[BTBL]
           ,[BTCODE]
           ,[PROCBATCH]
           ,[ePOSBATCH]
           ,[POSDATA]
           ,[BPOSDATA]
           ,[DTSTAMP]
           ,[BDTSTAMP]
           ,[ORGSYSTAN]
           ,[DTSTAMP_INSERT]
           ,[ProductID]
           ,[USERDATA]
           ,[BORGSYSTAN]
           ,[AUTHCODE]
           ,[CASHIERINFO]
           ,[DMID]
           ,[DTID]
           ,[CASHBACK]
           ,[BONUSRED]
           ,[PBGAMOUNT]
           ,[RRN]
		   from abc096.IMP_TRANSACT_D_monthly

		   truncate table abc096.IMP_TRANSACT_D_monthly

INSERT INTO [abc096].[LIFECARD_2019]
           ([TBL]
           ,[TCODE]
           ,[MID]
           ,[TID]
           ,[MASK]
           ,[AMOUNT]
           ,[CURR]
           ,[INST]
           ,[GRACE]
           ,[ORIGINATOR]
           ,[DESTCOMID]
           ,[PROCCODE]
           ,[MSGID]
           ,[RESPKIND]
           ,[REVERSED]
           ,[BTBL]
           ,[BTCODE]
           ,[PROCBATCH]
           ,[ePOSBATCH]
           ,[POSDATA]
           ,[BPOSDATA]
           ,[DTSTAMP]
           ,[BDTSTAMP]
           ,[ORGSYSTAN]
           ,[DTSTAMP_INSERT]
           ,[ProductID]
           ,[USERDATA]
           ,[BORGSYSTAN]
           ,[AUTHCODE]
           ,[CASHIERINFO]
           ,[DMID]
           ,[DTID]
           ,[CASHBACK]
           ,[BONUSRED]
           ,[PBGAMOUNT]
           ,[RRN])

	 select [TBL]
           ,[TCODE]
           ,[MID]
           ,[TID]
           ,[MASK]
           ,[AMOUNT]
           ,[CURR]
           ,[INST]
           ,[GRACE]
           ,[ORIGINATOR]
           ,[DESTCOMID]
           ,[PROCCODE]
           ,[MSGID]
           ,[RESPKIND]
           ,[REVERSED]
           ,[BTBL]
           ,[BTCODE]
           ,[PROCBATCH]
           ,[ePOSBATCH]
           ,[POSDATA]
           ,[BPOSDATA]
           ,[DTSTAMP]
           ,[BDTSTAMP]
           ,[ORGSYSTAN]
           ,[DTSTAMP_INSERT]
           ,[ProductID]
           ,[USERDATA]
           ,[BORGSYSTAN]
           ,[AUTHCODE]
           ,[CASHIERINFO]
           ,[DMID]
           ,[DTID]
           ,[CASHBACK]
           ,[BONUSRED]
           ,[PBGAMOUNT]
           ,[RRN]

		   from abc096.LIFECARD

		   delete from abc096.LIFECARD


       INSERT INTO [dbo].[TRANSLOG_TRANSACT_2019] with (TABLOCK)
                  ([MID]
                  ,[TID]
                  ,[DESTCOMID]
                  ,[TCODE]
                  ,[ORIGINATOR]
                  ,[INTERFACE]
                  ,[DTSTAMP]
                  ,[MSGID]
                  ,[TAMOUNT]
                  ,[TAUTHCODE]
                  ,[MASK]
                  ,[PROCCODE]
                  ,[INST]
                  ,[RESPKIND]
                  ,[TRESPONSE]
                  ,[USERDATA]
                  ,[DMID]
                  ,[DTID]
                  ,[PEM])

       select      [MID]
                  ,[TID]
                  ,[DESTCOMID]
                  ,[TCODE]
                  ,[ORIGINATOR]
                  ,[INTERFACE]
                  ,[DTSTAMP]
                  ,[MSGID]
                  ,[TAMOUNT]
                  ,[TAUTHCODE]
                  ,[MASK]
                  ,[PROCCODE]
                  ,[INST]
                  ,[RESPKIND]
                  ,[TRESPONSE]
                  ,[USERDATA]
                  ,[DMID]
                  ,[DTID]
                  ,[PEM]
       		   from dbo.TRANSLOG_TRANSACT

       		   truncate table dbo.TRANSLOG_TRANSACT


             INSERT INTO [dbo].[EasyPayAgent_2019]
                        ([Customer]
                        ,[TerminalID]
                        ,[StoreNo]
                        ,[TrxDate]
                        ,[TrxTime]
                        ,[EAN]
                        ,[Amount]
                        ,[Receipt]
                        ,[Trace]
                        ,[Serial]
                        ,[Exp Date]
                        ,[Type]
                        ,[UserName]
                        ,[Telephone]
                        ,[Result]
                        ,[ErrorCode]
                        ,[Status]
                        ,[MID]
                        ,[TrxCost]
                        ,[SecondaryPaymentCode]
                        ,[Reference]
                        ,[PAN financial]
                        ,[Installments financial]
                        ,[RRN financial])
                 select [Customer]
                        ,[TerminalID]
                        ,[StoreNo]
                        ,[TrxDate]
                        ,[TrxTime]
                        ,[EAN]
                        ,[Amount]
                        ,[Receipt]
                        ,[Trace]
                        ,[Serial]
                        ,[Exp Date]
                        ,[Type]
                        ,[UserName]
                        ,[Telephone]
                        ,[Result]
                        ,[ErrorCode]
                        ,[Status]
                        ,[MID]
                        ,[TrxCost]
                        ,[SecondaryPaymentCode]
                        ,[Reference]
                        ,[PAN financial]
                        ,[Installments financial]
                        ,[RRN financial]
             		   from dbo.EasyPayAgent

             		   delete from dbo.EasyPayAgent
