-- NOTOSInvoiceDetails.pdf
SELECT MIDs.MonthGroup, MIDs.[Group], TIDs.Shop, Banks.BANK, Sum(dbo.TRANSLOG_TRANSACT.TAMOUNT) AS SumOfTAMOUNT, [DTSTAMP] AS Period, Count(*) AS SumOfTrxNo
FROM (abc096.TIDs INNER JOIN (abc096.MIDs INNER JOIN dbo.TRANSLOG_TRANSACT ON MIDs.MID=dbo.TRANSLOG_TRANSACT.MID) ON TIDs.TID=dbo.TRANSLOG_TRANSACT.TID) INNER JOIN abc096.Banks  ON dbo.TRANSLOG_TRANSACT.DESTCOMID=Banks.DESTCOMID
WHERE (((dbo.TRANSLOG_TRANSACT.DTSTAMP) Between '2019-01-01 00:00:00.001' And '2019-02-01 00:00:00.001' ))
GROUP BY MIDs.MonthGroup, MIDs.[Group], TIDs.Shop, Banks.BANK, [DTSTAMP]
HAVING (((MIDs.[Group]) Like '%NOTOS%'))
ORDER BY MIDs.[Group], Banks.BANK;
