--- XalkiadakisInvoiceQuery.csv
SELECT A.Shop AS Shop, B.Terminals, B.Rent, A.Cost AS TransactionNum, A.trxTotal AS TransactionCost, Rent+trxTotal AS TotalCost
FROM 
 (SELECT shop, count(TIDs.Tid) AS Terminals, MonthRent*count(TIDs.Tid) AS Rent, monthrent 
  FROM abc096.TIDs WHERE TIDs.tid in 
    (SELECT abc096.TrxMonth.tid  from abc096.TrxMonth where abc096.TrxMonth.Destcomid='ALL' AND abc096.TrxMonth.mid='000000120004000') 
  GROUP BY shop, MonthRent)  AS B  
LEFT JOIN
 (SELECT Shop, sum(trxNo) AS Cost, sum(trxNo)*TrxCost AS trxTotal, monthrent FROM (abc096.TIDs LEFT JOIN abc096.TrxMonth ON abc096.TIDs.TID=abc096.TrxMonth.TID) LEFT JOIN abc096.MIDs ON abc096.TrxMonth.MID=MIDs.MID WHERE MIDs.mid='000000120004000' And abc096.TrxMonth.mid='000000120004000' GROUP BY shop, monthrent, TrxCost)  AS A ON (A.monthrent=B.monthrent) AND (B.SHOP=A.SHOP);
 

 ---  VASILOPOULOSInvoiceQuery.csv
 SELECT TIDs.Shop, Sum(abc096.TrxMonthVasilopoulos.TrxNo) AS SumOfTrxNo, abc096.TrxMonthVasilopoulos.Period
FROM dbo.AB_Stores RIGHT JOIN ((abc096.TrxMonthVasilopoulos LEFT JOIN abc096.TIDs ON abc096.TrxMonthVasilopoulos.TID = TIDs.TID) INNER JOIN abc096.Banks ON abc096.TrxMonthVasilopoulos.DESTCOMID = Banks.DESTCOMID) ON AB_Stores.Store = TIDs.Shop
GROUP BY TIDs.Shop, abc096.TrxMonthVasilopoulos.Period
ORDER BY TIDs.Shop;


--- TsakirisMallasInvoiceQuery
SELECT A.Shop AS Shop, B.Terminals, B.Rent, A.Cost AS TransactionNum, A.trxTotal AS TransactionCost, Rent+trxTotal AS TotalCost
FROM (SELECT shop, count(TIDs.Tid) AS Terminals, MonthRent*count(TIDs.Tid) AS Rent FROM abc096.TIDs WHERE TIDs.tid in (SELECT abc096.TrxMonth.tid  from abc096.TrxMonth where abc096.TrxMonth.Destcomid='ALL' AND abc096.TrxMonth.mid IN ('000000120004500','000000120004510','000000120004520','000000120004530')) GROUP BY shop, MonthRent)  AS B LEFT JOIN (SELECT Shop, sum(trxNo) AS Cost, sum(trxNo)*TrxCost AS trxTotal FROM (abc096.TIDs LEFT JOIN abc096.TrxMonth ON TIDs.TID=abc096.TrxMonth.TID) LEFT JOIN abc096.MIDs ON abc096.TrxMonth.MID=MIDs.MID WHERE MIDs.mid IN ('000000120004500','000000120004510','000000120004520','000000120004530') And abc096.TrxMonth.mid IN ('000000120004500','000000120004510','000000120004520','000000120004530') GROUP BY shop, monthrent, TrxCost)  AS A ON B.SHOP = A.SHOP;


--- METRO_TIDs
SELECT TIDs.TID, TIDs.Shop, MIDs.MID, abc096.MERCHANTS.store_code
FROM abc096.TIDs INNER JOIN (abc096.MIDs INNER JOIN abc096.MERCHANTS ON MIDs.MID=abc096.MERCHANTS.MID) ON TIDs.TID=abc096.MERCHANTS.TID
WHERE MIDs.MonthGroup Like '%metro%'
GROUP BY TIDs.TID, TIDs.Shop, MIDs.MID, abc096.MERCHANTS.store_code
ORDER BY TIDs.TID;


--- LeroyInvoiceQuery
SELECT A.Shop AS Shop, Terminals, Rent, Cost AS TransactionNum, trxTotal AS TransactionCost, Rent+trxTotal AS TotalCost
FROM (SELECT shop, count(TIDs.Tid) AS Terminals, MonthRent*count(TIDs.Tid) AS Rent FROM abc096.TIDs WHERE TIDs.tid in (SELECT abc096.TrxMonth.tid  from abc096.TrxMonth where abc096.TrxMonth.Destcomid='ALL' AND abc096.TrxMonth.mid='000000120002100') GROUP BY shop, MonthRent)  AS B LEFT JOIN (SELECT Shop, sum(trxNo) AS Cost, sum(trxNo)*TrxCost AS trxTotal FROM (abc096.TIDs LEFT JOIN abc096.TrxMonth ON TIDs.TID=abc096.TrxMonth.TID) LEFT JOIN abc096.MIDs ON abc096.TrxMonth.MID=MIDs.MID WHERE MIDs.mid='000000120002100' And abc096.TrxMonth.mid='000000120002100' GROUP BY shop, monthrent, TrxCost)  AS A ON a.SHOP=b.SHOP;


--- INTERSPORTInvoiceQuery
SELECT ePOSMonthTrx5.[Group], ePOSMonthTrx5.Descr, ePOSMonthTrx5.Terminals, ePOSMonthTrx5.MonthRent, ePOSMonthTrx5.TotRent, ePOSMonthTrx5.TrxNo, ePOSMonthTrx5.TrxCost, ePOSMonthTrx5.TotTrxCost, ePOSMonthTrx5.TotCost, ePOSMonthTrx5.Period, ePOSMonthTrx5.DateF, ePOSMonthTrx5.DateT
FROM ePOSMonthTrx5
WHERE [Group]='INTERSPORT';


---  AUTOTECHNICAInvoiceQuery
SELECT dbo.TRANSLOG_TRANSACT_temp.Mid AS MID, dbo.TRANSLOG_TRANSACT_temp.Tid AS TID, 
case TRANSLOG_TRANSACT_temp.DESTCOMID
when 'NET_EBNK' then 'EUROBANK'
when 'NET_ALPHA' then 'ALPHABANK'
when 'NET_ABC' then 'PIRAEUS BANK'
when 'NET_NTBN' then 'NATIONAL BANK'
end AS BANK, 
dbo.TRANSLOG_TRANSACT_temp.DTSTAMP, dbo.TRANSLOG_TRANSACT_temp.MSGID, dbo.TRANSLOG_TRANSACT_temp.TAMOUNT AS AMOUNT, dbo.TRANSLOG_TRANSACT_temp.TAUTHCODE AS AUTHCODE, dbo.TRANSLOG_TRANSACT_temp.MASK AS CARD, dbo.TRANSLOG_TRANSACT_temp.PROCCODE,
case
when left(PROCCODE,2)='00' then 'SALE'
when left(PROCCODE,2)='02' then 'VOID'
when left(PROCCODE,2)='20' then 'REFUND'
when left(PROCCODE,2)='22' then 'VOID REFUND'
 end AS [TYPE], 
dbo.TRANSLOG_TRANSACT_temp.INST, dbo.TRANSLOG_TRANSACT_temp.RESPKIND, dbo.TRANSLOG_TRANSACT_temp.TRESPONSE AS RESPONSE, dbo.TRANSLOG_TRANSACT_temp.DMID AS DESTMID, dbo.TRANSLOG_TRANSACT_temp.DTID AS DESTTID
FROM dbo.TRANSLOG_TRANSACT_temp
WHERE dbo.TRANSLOG_TRANSACT_temp.MID IN ('000000120004700','000000120004800')
ORDER BY dbo.TRANSLOG_TRANSACT_temp.DTSTAMP;


--- COUNT_LIFECARD
SELECT abc096.LIFECARD.DTSTAMP, abc096.LIFECARD.MID, abc096.LIFECARD.TID, abc096.LIFECARD.MASK, abc096.LIFECARD.AMOUNT
FROM abc096.LIFECARD
ORDER BY abc096.LIFECARD.DTSTAMP;


--- VIVAInvoiceQuery.csv
SELECT dbo.TRANSLOG_TRANSACT_temp.Mid AS VTID, 
case 
when DESTCOMID='NET_EBNK'   then 'EUROBANK'
when DESTCOMID='NET_ALPXML' then 'ALPHABANK'
when DESTCOMID='NET_ALPMOR' then 'ALPHABANK'
when DESTCOMID='NET_CITI'   then 'CITIBANK'
when DESTCOMID='NET_NTBN'   then 'NATIONAL BANK' end AS BANK, 
dbo.TRANSLOG_TRANSACT_temp.DTSTAMP, dbo.TRANSLOG_TRANSACT_temp.MSGID, dbo.TRANSLOG_TRANSACT_temp.TAMOUNT AS AMOUNT, dbo.TRANSLOG_TRANSACT_temp.TAUTHCODE AS AUTHCODE, dbo.TRANSLOG_TRANSACT_temp.MASK AS CARD,
 dbo.TRANSLOG_TRANSACT_temp.PROCCODE, dbo.TRANSLOG_TRANSACT_temp.INST, dbo.TRANSLOG_TRANSACT_temp.RESPKIND, dbo.TRANSLOG_TRANSACT_temp.TRESPONSE AS RESPONSE, dbo.TRANSLOG_TRANSACT_temp.DMID AS DESTMID, 
 dbo.TRANSLOG_TRANSACT_temp.DTID AS DESTTID
FROM dbo.TRANSLOG_TRANSACT_temp
WHERE (((dbo.TRANSLOG_TRANSACT_temp.MID) Like '00000008380%') Or ((dbo.TRANSLOG_TRANSACT_temp.MID)='000000160000001'))
ORDER BY dbo.TRANSLOG_TRANSACT_temp.DTSTAMP;


--- WINBankcsv
SELECT dbo.TRANSLOG_TRANSACT.Mid AS MID, dbo.TRANSLOG_TRANSACT.TID AS TID, 
case TRANSLOG_TRANSACT.DESTCOMID
when 'NET_EBNK' then 'EUROBANK'
when 'NET_ALPHA' then 'ALPHABANK'
when 'NET_CITI' then 'CITIBANK'
when 'NET_NTBN' then 'NATIONAL BANK'
end AS BANK,
dbo.TRANSLOG_TRANSACT.DTSTAMP, dbo.TRANSLOG_TRANSACT.MSGID, dbo.TRANSLOG_TRANSACT.TAMOUNT AS AMOUNT, 
dbo.TRANSLOG_TRANSACT.TAUTHCODE AS AUTHCODE, dbo.TRANSLOG_TRANSACT.MASK AS CARD, dbo.TRANSLOG_TRANSACT.PROCCODE, dbo.TRANSLOG_TRANSACT.INST, dbo.TRANSLOG_TRANSACT.RESPKIND, dbo.TRANSLOG_TRANSACT.TRESPONSE AS RESPONSE,
 dbo.TRANSLOG_TRANSACT.DMID AS DESTMID, dbo.TRANSLOG_TRANSACT.DTID AS DESTTID
FROM dbo.TRANSLOG_TRANSACT
WHERE dbo.TRANSLOG_TRANSACT.originator = 'DIAL_03'
ORDER BY dbo.TRANSLOG_TRANSACT.DTSTAMP;


--- ePOSMonthDutyFreeTerminals
SELECT abc096.MERCHANTS.Mid, abc096.MERCHANTS.TID,
CASE
WHEN abc096.MERCHANTS.UPLOADHOSTNAME='NET_EBNK'     THEN 'EUROBANK'
WHEN abc096.MERCHANTS.UPLOADHOSTNAME='NET_ABC'      THEN 'PIRAEUS BANK'
WHEN abc096.MERCHANTS.UPLOADHOSTNAME='NET_ALPHA'    THEN 'ALPHABANK'
WHEN abc096.MERCHANTS.UPLOADHOSTNAME='NET_AGROTIKI' THEN 'AGROTIKI'
WHEN abc096.MERCHANTS.UPLOADHOSTNAME='NET_NTBN'     THEN 'NATIONAL BANK' 
END AS BANK, 
abc096.MERCHANTS.DMID, abc096.MERCHANTS.MERCHTITLE, abc096.MERCHANTS.MERCHADDRESS
FROM abc096.MERCHANTS
WHERE (((abc096.MERCHANTS.MID)='000000120002800' Or (abc096.MERCHANTS.MID)='000000120003500' Or (abc096.MERCHANTS.MID)='000000120003510'))
GROUP BY abc096.MERCHANTS.Mid, abc096.MERCHANTS.TID, abc096.MERCHANTS.UPLOADHOSTNAME, abc096.MERCHANTS.DMID, abc096.MERCHANTS.MERCHTITLE, abc096.MERCHANTS.MERCHADDRESS
ORDER BY abc096.MERCHANTS.Mid, abc096.MERCHANTS.TID, abc096.MERCHANTS.UPLOADHOSTNAME;


--- COUNT_GO4MORE_LTY.xlsx
SELECT dbo.TRANSLOG_TRANSACT_temp.DTSTAMP, dbo.TRANSLOG_TRANSACT_temp.MID, dbo.TRANSLOG_TRANSACT_temp.TID, dbo.TRANSLOG_TRANSACT_temp.MSGID, dbo.TRANSLOG_TRANSACT_temp.DESTCOMID, dbo.TRANSLOG_TRANSACT_temp.PROCCODE, dbo.TRANSLOG_TRANSACT_temp.MASK, dbo.TRANSLOG_TRANSACT_temp.TAMOUNT, dbo.TRANSLOG_TRANSACT_temp.TAUTHCODE
FROM dbo.TRANSLOG_TRANSACT_temp
WHERE dbo.TRANSLOG_TRANSACT_temp.DESTCOMID='NET_NTBNLTY' AND PROCCODE IN ('000000','020000')
ORDER BY dbo.TRANSLOG_TRANSACT_temp.DTSTAMP;


--- COUNT_EUROBANK_LTY.xlsx
SELECT dbo.TRANSLOG_TRANSACT_temp.DTSTAMP, dbo.TRANSLOG_TRANSACT_temp.MID, dbo.TRANSLOG_TRANSACT_temp.TID, dbo.TRANSLOG_TRANSACT_temp.MSGID, dbo.TRANSLOG_TRANSACT_temp.DESTCOMID, dbo.TRANSLOG_TRANSACT_temp.PROCCODE, dbo.TRANSLOG_TRANSACT_temp.MASK, dbo.TRANSLOG_TRANSACT_temp.TAMOUNT, dbo.TRANSLOG_TRANSACT_temp.TAUTHCODE
FROM dbo.TRANSLOG_TRANSACT_temp
WHERE dbo.TRANSLOG_TRANSACT_temp.DESTCOMID='NET_EBLY1' OR dbo.TRANSLOG_TRANSACT_temp.DESTCOMID='NET_EBLY'
ORDER BY dbo.TRANSLOG_TRANSACT_temp.DTSTAMP;


--- COUNT_ALPHA_LTY.xlsx
SELECT dbo.TRANSLOG_TRANSACT_temp.DTSTAMP, dbo.TRANSLOG_TRANSACT_temp.MID, dbo.TRANSLOG_TRANSACT_temp.TID, dbo.TRANSLOG_TRANSACT_temp.MSGID, dbo.TRANSLOG_TRANSACT_temp.PROCCODE, dbo.TRANSLOG_TRANSACT_temp.MASK, dbo.TRANSLOG_TRANSACT_temp.TAMOUNT, dbo.TRANSLOG_TRANSACT_temp.TAUTHCODE, dbo.TRANSLOG_TRANSACT_temp.USERDATA
FROM dbo.TRANSLOG_TRANSACT_temp
WHERE dbo.TRANSLOG_TRANSACT_temp.USERDATA IS NOT NULL AND dbo.TRANSLOG_TRANSACT_temp.USERDATA<>'000000000000000' AND dbo.TRANSLOG_TRANSACT_temp.USERDATA<>''
ORDER BY dbo.TRANSLOG_TRANSACT_temp.DTSTAMP;
