SELECT
 dbo.TRANSLOG_TRANSACT_2018.Mid AS MID,
 dbo.TRANSLOG_TRANSACT_2018.TID AS TID,
 case
 when [DESTCOMID]='NET_EBNK' then 'EUROBANK'
 when [DESTCOMID]='NET_ALPHA' then'ALPHABANK'
 when [DESTCOMID]='NET_CITI' then'CITIBANK'
 when [DESTCOMID]='NET_NTBN' then 'NATIONAL BANK'
 end  AS BANK,
 dbo.TRANSLOG_TRANSACT_2018.DTSTAMP,
 dbo.TRANSLOG_TRANSACT_2018.MSGID,
 dbo.TRANSLOG_TRANSACT_2018.TAMOUNT AS AMOUNT,
 dbo.TRANSLOG_TRANSACT_2018.TAUTHCODE AS AUTHCODE,
 dbo.TRANSLOG_TRANSACT_2018.MASK AS CARD,
 dbo.TRANSLOG_TRANSACT_2018.PROCCODE,
 dbo.TRANSLOG_TRANSACT_2018.INST,
 dbo.TRANSLOG_TRANSACT_2018.RESPKIND,
 dbo.TRANSLOG_TRANSACT_2018.TRESPONSE AS RESPONSE,
 dbo.TRANSLOG_TRANSACT_2018.DMID AS DESTMID,
 dbo.TRANSLOG_TRANSACT_2018.DTID AS DESTTID
FROM dbo.TRANSLOG_TRANSACT_2018
WHERE dbo.TRANSLOG_TRANSACT_2018.originator = 'DIAL_03'
 and DTSTAMP < '2018-03-01 00:00:01'
ORDER BY dbo.TRANSLOG_TRANSACT_2018.DTSTAMP;
