
SELECT ter_tid,TER_START_FILE_DL,TER_UNSUCC_FILE_DL, TER_SUCC_FILE_DL,TER_START_PARAM_DL, TER_UNSUCC_PARAM_DL, TER_SUCC_PARAM_DL
 FROM
 (select EPA_TERMINAL from TERM_EASYPAYSERVICES
  where EPA_EPA_ENABLED= '1') q
  JOIN TERMINAL A ON Q.EPA_TERMINAL = A.TER_TID
WHERE q.EPA_TERMINAL  not   IN
  (SELECT TERMINAL.TER_TID
  FROM TERMINAL
  WHERE TERMINAL.TER_START_FILE_DL > '26/06/18'
  AND (TERMINAL.TER_UNSUCC_FILE_DL < TERMINAL.TER_START_FILE_DL
  OR TERMINAL.TER_UNSUCC_FILE_DL  IS NULL)
  )
