select MERCHTITLE,MERCHADDRESS,STORE_CODE,
(CASE UPLOADHOSTNAME
WHEN 'NET_ABC'      THEN 'Piraeus Bank'
WHEN 'NET_CITI'     THEN 'CitiBank'
WHEN 'NET_CMBN'     THEN 'Commercial Bank'
WHEN 'NET_AGROTIKI' THEN 'Agrotiki Bank'
WHEN 'NET_NTBN'     THEN 'National Bank of Greece'
WHEN 'NET_ALPHA'    THEN 'Alpha Bank'
WHEN 'NET_EBNK'     THEN 'Eurobank'
WHEN 'NET_GENIKI'   THEN 'Geniki Bank'
ELSE 'UNKNOWN BANK'
END) as 'Bank',
DMID
 from abc096.MERCHANTS
where mid = '000000120002800'
group by DMID,MERCHTITLE,MERCHADDRESS, UPLOADHOSTNAME,STORE_CODE
order  by MERCHADDRESS
