delete from  dbo.MERCHBINS_TEST;
delete from  dbo.MERCHANTS_test;
delete from  dbo.LOADBALANCE_test;

INSERT INTO zacrpt_test.[dbo].[MERCHBINS_TEST]
           ([TID]
           ,[MID]
           ,[DESTPORT]
           ,[BINLOWER]
           ,[BINUPPER]
           ,[INSTMIN]
           ,[INSTMAX]
           ,[GRACEMIN]
           ,[GRACEMAX]
           ,[ALLOWED]
           ,[SYNC_ID]
           ,[AMOUNTMIN]
           ,[AMOUNTMAX])
		   select  [TID]
           ,[MID]
           ,[DESTPORT]
           ,[BINLOWER]
           ,[BINUPPER]
           ,[INSTMIN]
           ,[INSTMAX]
           ,[GRACEMIN]
           ,[GRACEMAX]
           ,[ALLOWED]
           ,[SYNC_ID]
           ,[AMOUNTMIN]
           ,[AMOUNTMAX]
		    from zacrpt.dbo.MERCHBINS;

INSERT INTO zacrpt_test.[dbo].[MERCHANTS_test]
           ([MID]
           ,[TID]
           ,[CARDTYPE]
           ,[UPLOADHOSTID]
           ,[STORENUM]
           ,[TERMNUM]
           ,[MDCMID]
           ,[MERCHTITLE]
           ,[MERCHADDRESS]
           ,[DEFCURRENCY]
           ,[RECONCURRENCY]
           ,[SESSIONNUM]
           ,[LASTRECONDATE]
           ,[LASTRECONSTATUS]
           ,[BANKCODES]
           ,[MERCHNAME]
           ,[MERCHCITY]
           ,[MERCHSTATE]
           ,[MERCHTYPE]
           ,[MERCHLOCATION]
           ,[MERCHPOSTAL]
           ,[MERCHCOUNTRY]
           ,[MERCHSECURITY]
           ,[AUTHHOST]
           ,[LASTZACTAN]
           ,[DESTTID]
           ,[DESTADDRESS]
           ,[CREATED_DATE]
           ,[PERIODIC_LIMIT]
           ,[VALOCITY_LIMIT]
           ,[FLOOR_LIMIT]
           ,[CURRENT_SYSTAN]
           ,[ALLOWED_ACTIONS]
           ,[ACTIVE]
           ,[INSTALLMENTS]
           ,[SYNC_ID]
           ,[STORE_CODE]
           ,[USERNAME]
           ,[PASSWRD]
           ,[PW_CHANGEDATE]
           ,[DCC_PRIORITY]
           ,[GMAXINST]
           ,[BINRULING]
           ,[LOYALTY_ENTRY]
           ,[DCC_ENTRY])
     select [MID]
           ,[TID]
           ,[CARDTYPE]
           ,[UPLOADHOSTID]
           ,[STORENUM]
           ,[TERMNUM]
           ,[MDCMID]
           ,[MERCHTITLE]
           ,[MERCHADDRESS]
           ,[DEFCURRENCY]
           ,[RECONCURRENCY]
           ,[SESSIONNUM]
           ,[LASTRECONDATE]
           ,[LASTRECONSTATUS]
           ,[BANKCODES]
           ,[MERCHNAME]
           ,[MERCHCITY]
           ,[MERCHSTATE]
           ,[MERCHTYPE]
           ,[MERCHLOCATION]
           ,[MERCHPOSTAL]
           ,[MERCHCOUNTRY]
           ,[MERCHSECURITY]
           ,[AUTHHOST]
           ,[LASTZACTAN]
           ,[DESTTID]
           ,[DESTADDRESS]
           ,[CREATED_DATE]
           ,[PERIODIC_LIMIT]
           ,[VALOCITY_LIMIT]
           ,[FLOOR_LIMIT]
           ,[CURRENT_SYSTAN]
           ,[ALLOWED_ACTIONS]
           ,[ACTIVE]
           ,[INSTALLMENTS]
           ,[SYNC_ID]
           ,[STORE_CODE]
           ,[USERNAME]
           ,[PASSWRD]
           ,[PW_CHANGEDATE]
           ,[DCC_PRIORITY]
           ,[GMAXINST]
           ,[BINRULING]
           ,[LOYALTY_ENTRY]
           ,[DCC_ENTRY]
		   from zacrpt.[dbo].[MERCHANTS]

INSERT INTO zacrpt_test.[dbo].[LOADBALANCE_test]
           ([BALANCEGROUP]
           ,[DESTPORT]
           ,[LOADTYPE]
           ,[LOADVALUE]
           ,[SYNC_ID])
    select  [BALANCEGROUP]
           ,[DESTPORT]
           ,[LOADTYPE]
           ,[LOADVALUE]
           ,[SYNC_ID]
		   from zacrpt.[dbo].[LOADBALANCE]
