USE [ZacReporting]
GO

--delete from [abc096].[IMP_TRANSACT_D_tempLN]

INSERT INTO [abc096].[IMP_TRANSACT_D_tempLN]
           ([TBL]
           ,[TCODE]
           ,[MID]
           ,[TID]
           ,[MASK]
           ,[AMOUNT]
           ,[CURR]
           ,[INST]
           ,[GRACE]
           ,[ORIGINATOR]
           ,[DESTCOMID]
           ,[PROCCODE]
           ,[MSGID]
           ,[RESPKIND]
           ,[REVERSED]
           ,[BTBL]
           ,[BTCODE]
           ,[PROCBATCH]
           ,[ePOSBATCH]
           ,[POSDATA]
           ,[BPOSDATA]
           ,[DTSTAMP]
           ,[BDTSTAMP]
           ,[ORGSYSTAN]
           ,[DTSTAMP_INSERT]
           ,[ProductID]
           ,[USERDATA]
           ,[BORGSYSTAN]
           ,[AUTHCODE]
           ,[CASHIERINFO]
           ,[DMID]
           ,[DTID]
           ,[CASHBACK]
           ,[BONUSRED]
           ,[PBGAMOUNT]
           ,[RRN]
           ,[DCC_CURRENCY]
           ,[DCC_AMOUNT]
           ,[DCCCHOSEN_DCCELIGIBLE])
    select [TBL]
           ,[TCODE]
           ,[MID]
           ,[TID]
           ,[MASK]
           ,[AMOUNT]
           ,[CURR]
           ,[INST]
           ,[GRACE]
           ,[ORIGINATOR]
           ,[DESTCOMID]
           ,[PROCCODE]
           ,[MSGID]
           ,[RESPKIND]
           ,[REVERSED]
           ,[BTBL]
           ,[BTCODE]
           ,[PROCBATCH]
           ,[ePOSBATCH]
           ,[POSDATA]
           ,[BPOSDATA]
           ,[DTSTAMP]
           ,[BDTSTAMP]
           ,[ORGSYSTAN]
           ,[DTSTAMP_INSERT]
           ,[ProductID]
           ,[USERDATA]
           ,[BORGSYSTAN]
           ,[AUTHCODE]
           ,[CASHIERINFO]
           ,[DMID]
           ,[DTID]
           ,[CASHBACK]
           ,[BONUSRED]
           ,[PBGAMOUNT]
           ,[RRN]
           ,[DCC_CURRENCY]
           ,[DCC_AMOUNT]
           ,[DCCCHOSEN_DCCELIGIBLE]
		   from abc096.IMP_TRANSACT_D
		   where mid in ('000000001100001','000000001100010','000000001100011','000000001100013','000000001100014','000000001100015','000000001100016','000000001100017','000000001100018','000000001100019','000000001100020')
		   --and dtstamp>='2018-05-07 00:00:00.001'
GO
